---
title: "Parameterized Document with React and Plumber"
params:
  data: file.csv
  stocks: '["AAPL", "MO"]'
  html_page: TRUE
  title: Stock Stuff
output:
  html_document: default
  pdf_document: default
---

What the YAML looks like
```
---
title: "My Document"
params:
  data: file.csv
  stocks: '["AAPL", "MO", "AMZN"]'
  html_page: TRUE
  title: Stock Stuff
output:
  html_document: default
  pdf_document: default
---
```

```{r}
stock_vector <- jsonlite::fromJSON(params$stocks)
print(params)
```

## Will evaluate if more than 1 stock selected.
```{r}
knitr::opts_chunk$set(eval = (length(stock_vector) >= 2), message=FALSE, warning=FALSE )
```

## `r params$title`

```{r}
library(tidyquant)
library(ggplot2)
library(tidyverse)
```


```{r}
print(params)

stocks <- tq_get(stock_vector)

glimpse(stocks)

gg <- 
  ggplot(stocks) +
  aes(x = date, y = close, colour = symbol) +
  geom_line()
  
  print(gg)
```

```{r}
stocks %>% 
  select(date, symbol, adjusted) %>% 
  pivot_wider(names_from = symbol, values_from = c(
    adjusted
  )) %>% 
  select_if(is.numeric) %>% 
  cor

```

```{r}

```
